# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YoutubeSearchBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 815)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchPatternEdit = QtWidgets.QLineEdit(self.widget_2)
        self.searchPatternEdit.setObjectName("searchPatternEdit")
        self.horizontalLayout_2.addWidget(self.searchPatternEdit)
        self.searchButton = QtWidgets.QPushButton(self.widget_2)
        icon = QtGui.QIcon.fromTheme("Search")
        self.searchButton.setIcon(icon)
        self.searchButton.setFlat(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchResultList = QtWidgets.QListWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchResultList.sizePolicy().hasHeightForWidth())
        self.searchResultList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        self.searchResultList.setFont(font)
        self.searchResultList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchResultList.setProperty("showDropIndicator", True)
        self.searchResultList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.searchResultList.setResizeMode(QtWidgets.QListView.Adjust)
        self.searchResultList.setViewMode(QtWidgets.QListView.ListMode)
        self.searchResultList.setSelectionRectVisible(True)
        self.searchResultList.setObjectName("searchResultList")
        self.horizontalLayout_3.addWidget(self.searchResultList)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadAudioButton = QtWidgets.QPushButton(self.widget)
        self.loadAudioButton.setObjectName("loadAudioButton")
        self.horizontalLayout.addWidget(self.loadAudioButton)
        self.loadVideoButton = QtWidgets.QPushButton(self.widget)
        self.loadVideoButton.setObjectName("loadVideoButton")
        self.horizontalLayout.addWidget(self.loadVideoButton)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Youtube Download"))
        self.searchButton.setText(_translate("Dialog", "..."))
        self.loadAudioButton.setText(_translate("Dialog", "load audio"))
        self.loadVideoButton.setText(_translate("Dialog", "load video"))
