# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlarmTimeBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(513, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SelectFrame = QtWidgets.QFrame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectFrame.sizePolicy().hasHeightForWidth())
        self.SelectFrame.setSizePolicy(sizePolicy)
        self.SelectFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SelectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SelectFrame.setObjectName("SelectFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SelectFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.oneTimeButton = QtWidgets.QRadioButton(self.SelectFrame)
        self.oneTimeButton.setObjectName("oneTimeButton")
        self.verticalLayout_3.addWidget(self.oneTimeButton)
        self.repeatButton = QtWidgets.QRadioButton(self.SelectFrame)
        self.repeatButton.setObjectName("repeatButton")
        self.verticalLayout_3.addWidget(self.repeatButton)
        self.horizontalLayout.addWidget(self.SelectFrame)
        self.SettingsFrame2 = QtWidgets.QFrame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsFrame2.sizePolicy().hasHeightForWidth())
        self.SettingsFrame2.setSizePolicy(sizePolicy)
        self.SettingsFrame2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SettingsFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SettingsFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingsFrame2.setObjectName("SettingsFrame2")
        self.horizontalLayout.addWidget(self.SettingsFrame2)
        self.SettingsFrame1 = QtWidgets.QFrame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsFrame1.sizePolicy().hasHeightForWidth())
        self.SettingsFrame1.setSizePolicy(sizePolicy)
        self.SettingsFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SettingsFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingsFrame1.setObjectName("SettingsFrame1")
        self.horizontalLayout.addWidget(self.SettingsFrame1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.oneTimeButton.setText(_translate("Frame", "One time"))
        self.repeatButton.setText(_translate("Frame", "repeatedly"))
